# Generated by Django 2.2.16 on 2020-10-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='name',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
