# Generated by Django 2.2.16 on 2020-10-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201014_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='name',
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
